[[coremoduletarget-reference]]
== Module Target

[[coremoduletarget-overview]]
=== Overview
Module Target represent the firmware that will be compiled and deployed to a module.

Module Targets are processed by the link:../tools/index.html#coretools-coreworkspace[CoreWorkspace.py] command line tool.

From a Core user point of view a target is nothing but a directory that meets the following requirements:

. it contains a file named `MODULE_TARGET.json`
. it have a well defined structure

[[coremoduletarget-json]]
=== MODULE_TARGET.json
.Example: `MODULE_TARGET.json` for an IMU target
[source,json,numbered]
----
{
  "name": "imu", <1>
  "description": "IMU", <2>
  "module": "imu", <3>
  "required_packages": [ <4>
    "led",
    "balancing_robot",
    "actuator_msgs",
    "differential_drive_msgs",
    "sensor_msgs",
    "pid",
    "pid_msgs"
  ],
  "sources": [ <5>
    "main.cpp"
  ],
  "includes": [] <6>
}
----
<1> the `name` of the target; it will be used as the module name
<2> a brief description
<3> the module on which the firmware will run
<4> list of required packages
<5> list of source files to be compiled (relative to target directory)
<6> list of include directories for header files (relative to target directory)

[[coremoduletarget-generated]]
=== Generated file
Module Target are converted to CMake footnoteref:[CMAKE, CMake https://cmake.org/] code using the command line tools.

.Example: `CMakeLists.txt` generated from `MODULE_TARGET.json`
[source,cmake,numbered]
----
# Generated by ModuleTarget.py
# Remove a "#" from the line below to stop generating this file every time you call CoreWorkspace generate
## TARGET MODULE imu <1>

PROJECT( imu )
CMAKE_MINIMUM_REQUIRED(VERSION 2.8)

FIND_PACKAGE( CORE_BUILD CONFIG REQUIRED )

INCLUDE ( CoreTarget NO_POLICY_SCOPE )
SET( PROJECT_INCLUDE_DIRECTORIES
)

SET( PROJECT_SOURCES
  main.cpp
)

core_target_module(
  MODULE imu
  PACKAGES
    led
    balancing_robot
    actuator_msgs
    differential_drive_msgs
    sensor_msgs
    pid
    pid_msgs
)
----
<1> remove a `#` to stop generating this file every time you call `CoreWorkspace generate`

WARNING: `CMakeLists.txt` file is generated every time *if* it contains a line starting with `## TARGET MODULE`