language: ruby
rvm:
    - 2.1.5
install:
    - gem install asciidoctor
    - gem install asciidoctor-diagram
    - gem install coderay
    - sudo apt-get install -y graphviz
script:
    - mkdir site 
    - cd docs
    - asciidoctor -r asciidoctor-diagram -a experimental -a toc=left -a toclevels=3 -a icons=font -a source-highlighter=coderay -a plantuml_format=png -D ../site index.ad 
    - cd core
    - asciidoctor -r asciidoctor-diagram -a experimental -a toc=left -a toclevels=3 -a icons=font -a source-highlighter=coderay -a plantuml_format=png -D ../../site/core index.ad 
    - cd ..
    - cd mw
    - asciidoctor -r asciidoctor-diagram -a experimental -a toc=left -a toclevels=3 -a icons=font -a source-highlighter=coderay -a plantuml_format=png -D ../../site/mw index.ad 
    - cd ..
    - cd tools
    - asciidoctor -r asciidoctor-diagram -a experimental -a toc=left -a toclevels=3 -a icons=font -a source-highlighter=coderay -a plantuml_format=png -D ../../site/tools index.ad 
    - cd ..
    - cd getting-started
    - asciidoctor -r asciidoctor-diagram -a experimental -a toc=left -a toclevels=3 -a icons=font -a source-highlighter=coderay -a plantuml_format=png -D ../../site/getting-started index.ad 
    - cd ..
    - cd tutorials
    - asciidoctor -r asciidoctor-diagram -a experimental -a toc=left -a toclevels=3 -a icons=font -a source-highlighter=coderay -a plantuml_format=png -D ../../site/tutorials index.ad 
    - cd ..
    - cd ..
    - cd site
    - find . -name "*.cache" | xargs rm -f
    - cd ..
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: docs.novalabs.io
    endpoint: docs.novalabs.io.s3-website.eu-central-1.amazonaws.com
    region: eu-central-1
    skip_cleanup: true
    local-dir: site
    acl: public_read
    detect_encoding: true
notifications:
    email:
        on_failure: always


