language: ruby
rvm:
    - 2.1.5
install:
    - gem install asciidoctor
    - gem install asciidoctor-diagram
    - gem install coderay
    - sudo apt-get install -y graphviz
script:
    - make
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: docs.novalabs.io
    endpoint: docs.novalabs.io.s3-website.eu-central-1.amazonaws.com
    region: eu-central-1
    skip_cleanup: true
    local-dir: html
    acl: public_read
    detect_encoding: true
notifications:
    email:
        on_failure: always


