[[tutorial-workspace]]
== Working with the workspace

[[tutorial-workspace-overview]]
=== Overview
In this tutorial we will learn how to use the CLI tools to manage a workspace.

[[tutorial-workspace-initialization]]
=== Step I: initialization
A workspace is nothing but a structured directory with a JSON file inside (link:../core/index.html#coreworkspace-reference[here] there are the details).

To create the structure and the JSON file the `CoreWorkspace.py initialize` command is provided.

.Creating an empty workspace
=================
[listing.console]
----
$ mkdir my_workspace
$ cd my_workspace
$ CoreWorkspace.py initialize
----
The expected output is:
----
Workspace initialized.
You can now do a 'source setup.sh'

SUCCESS
=================

The workspace now contains the following folders:

=================
[listing.console]
.
├── build
│   ├── debug
│   ├── params
│   └── release
├── generated
│   ├── modules
│   ├── packages
│   └── params
├── setup.sh
├── src
│   ├── modules
│   ├── packages
│   ├── params
│   └── targets
└── WORKSPACE.json
=================

A `setup.sh` file is also generated. This files sets the environments variable needed by the workspace. It includes the Core `setup.sh` file, so you just need to source it.

TIP: use the `--force` option to re-create the JSON and setup.sh files, without touching the contents of the workspace. It is useful, for example, if you move either the Core distribution or the workspace.

[[tutorial-workspace-target]]
=== Step II: add a target
An empty workspace is pretty useless, so the first thing to do is to add a target to it (link:../core/index.html#coremoduletarget-reference[here] there are the details).

To add a target to the workspace the `CoreWorkspace.py target add` command is provided. The first parameter specifies the target type (i.e., the Core module to which the code will be deployed), while the second parameter specifies the name of the target instance in your workspace (i.e., motor_test)

.Adding a target
=================
[listing.console]
----
$ source setup.sh
$ CoreWorkspace.py target add udc motor_test
----
The expected output is:
----
Using Core module 'udc'

SUCCESS
=================

The workspace content now is:

=================
[listing.console]
.
├── build
│   ├── debug
│   ├── params
│   └── release
├── generated
│   ├── modules
│   ├── packages
│   └── params
├── setup.sh
├── src
│   ├── modules
│   ├── packages
│   ├── params
│   │   └── motor_test
│   │       └── default.json
│   └── targets
│       └── motor_test
│           ├── main.cpp
│           ├── MODULE_TARGET.json
│           ├── PARAMETERS.default.json
│           └── PARAMETERS.json
└── WORKSPACE.json
=================

[[tutorial-workspace-ls]]
=== Step III: inspecting the workspace
Now we have something in the workspace. But what do we have exactly?

To inspect the content of a workspace the `CoreWorkspace.py ls` command is provided.
It lists the content of the workspace, and all the dependencies needed to build it.

.Inspecting the workspace
=================
[listing.console]
----
$ CoreWorkspace.py ls
----

The expected output is:

----
= WORKSPACE

== PARAMETERS

Type: motor_test
Name: uDC module template configuration
Description: src/targets/motor_test

== PACKAGE DEPENDENCIES

Package: MC33926_driver
Source: Core
Notes: 

Package: QEI_driver
Source: Core
Notes: 

...

== MODULE DEPENDENCIES

Module: udc
Source: Core
Notes: 

== MODULE TARGETS

Type: application
Name: motor_test
Description: motor_test
Module: udc
OS Version: CHIBIOS_16
Root: src/targets/motor_test
Status: OK

== PARAMETER TARGETS

Name: default
Description: Default configuration
Parameters: motor_test
Root: src/params
Status: OK

SUCCESS
----
=================

[[tutorial-workspace-generate]]
=== Step IV: generate
Now that we have a workspace and a target, it is time to generate the corresponding files: the code, CMake files, Documentation, Eclipse project.

To generate the code `CoreWorkspace.py generate` command is provided.
All the generated files will be inside the `generated` directory.

.Generate
=================
[listing.console]
----
$ CoreWorkspace.py generate
----
The command output shows details about allgenerated code.
=================


[[tutorial-workspace-build]]
=== Step V: build
Now that we have the generated source code, we can build the targets.

To build a target, you must call `make` from its build directory.

.Building a target
=================
[listing.console]
----
$ cd build/debug/motor_test
$ make
----
The output will show the compile process, and a successfull build will finish with:
----
[100%] Linking CXX executable firmware
[100%] Built target firmware
----
=================