[[middleware-module]]
== Module
`core::mw::CoreModule` abstracts a Core module. 

Each module must inherit from this class.

.`CoreModule` header file
[source,cpp,numbered]
----
// Led::toggle and Led::write are to be implemented in derived Module.

#pragma once

#include <core/mw/namespace.hpp>
#include <core/mw/common.hpp>
#include <core/mw/CoreNodeManager.hpp>

NAMESPACE_CORE_MW_BEGIN

class CoreModule:
	public CoreNodeManager <1>
{
public:
	class Led <2>
	{
	public:
		void
		toggle();

		void
		write(
			unsigned on
		);
	};

	static Led& led;


	bool
	initialize();

	static const void
	halt(
		const char* message
	);


	CoreModule() {}

	virtual ~CoreModule() {}
};

NAMESPACE_CORE_MW_END
----
<1> inherits from `core::mw::CoreNodeManager`
<2> led class

Lines 15-25 define the class that control the status led.
The implementation of the class is left to the derived module.


.A module derived from `CoreNode`
=================
[source,cpp,numbered]
----
#pragma once

#include <core/mw/CoreModule.hpp>
#include <ModuleConfiguration.hpp>

namespace core {
namespace hw {
class Pad;
class SPIDevice;
class I2CMaster;
class EXTChannel;
}
}

class Module:
	public core::mw::CoreModule <1>
{
public:
	static bool
	initialize(); <2>

// --- DEVICES ----------------------------------------------------------------
	static core::hw::Pad& d0;
	static core::hw::Pad& d1;
	static core::hw::Pad& d2;
	static core::hw::Pad& d3;
	static core::hw::Pad& d4;
	static core::hw::Pad& d5;
	static core::hw::Pad& d6;
	static core::hw::Pad& d7;

	static core::hw::SPIDevice& spi;
	static core::hw::I2CMaster& i2c;
// ----------------------------------------------------------------------------

	Module();
	virtual ~Module() {}
};
----
<1> inherit from `CoreModule`
<2> override `CoreModule::intialize()`
=================

.Using a module derived from `CoreNode`
=================
The following is the `main.cpp` from a target using the IO module.

[source,cpp,numbered]
----
#include <ModuleConfiguration.hpp>
#include <Module.hpp> <1>

// MESSAGES
#include <core/common_msgs/Led.hpp>

// NODES
#include <core/led/Subscriber.hpp>

// BOARD IMPL
#include <core/hw/EXT.hpp> <2>
#include <core/hw/GPIO.hpp>
#include <core/hw/SPI.hpp>
#include <core/hw/I2C.hpp>

// *** DO NOT MOVE ***
Module module; <3>

// TYPES

// NODES
core::led::Subscriber led_subscriber("led_subscriber", core::os::Thread::PriorityEnum::LOWEST); <4>

// MAIN
extern "C" {
	int
	main()
	{
		module.initialize(); <5>

		// Led subscriber node
		core::led::SubscriberConfiguration led_subscriber_configuration;
		led_subscriber_configuration.topic = "led";
		led_subscriber.setConfiguration(led_subscriber_configuration); <6>
		module.add(led_subscriber); <7>

		// Setup and run
		module.setup(); <8>
		module.run(); <9>

		// Is everything going well?
		for (;;) {
			if (!module.isOk()) { <10>
				module.halt("This must not happen!");
			}

			core::os::Thread::sleep(core::os::Time::ms(500));
		}

		return core::os::Thread::OK;
	    }
}


----
<1> include the header file for the derived module
<2> include the implementation of the forward declarations in `Module.hpp`
<3> module instance
<4> nodes instances
<5> initialize the module
<6> configure the nodes
<7> add nodes to the module
<8> setup the nodes
<9> run the nodes
<10> check that everything is ok
=================
